# Generated by Django 4.0.2 on 2022-02-19 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_type', models.CharField(choices=[('A', 'Album'), ('S', 'Single'), ('C', 'compilation')], max_length=10)),
                ('name', models.CharField(max_length=90)),
                ('release_date', models.DateField()),
                ('followers', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveBigIntegerField()),
                ('explicit', models.BooleanField()),
                ('is_playable', models.BooleanField()),
                ('popularity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(default='Track', max_length=10)),
            ],
        ),
    ]
