# Generated by Django 4.0.2 on 2022-02-19 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=155)),
                ('genres', models.CharField(choices=[('P', 'Pop'), ('H', 'Hip Hop'), ('R', 'Rock'), ('N', 'RnB'), ('S', 'Soul'), ('J', 'Jazz'), ('C', 'Country'), ('D', 'Disco')], max_length=10)),
                ('popularity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(default='artist', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumtypes', models.CharField(choices=[('A', 'Album'), ('S', 'Single'), ('C', 'Compilation')], max_length=1)),
                ('name', models.CharField(max_length=90)),
                ('release_date', models.DateField()),
                ('duration_ms', models.PositiveBigIntegerField()),
                ('explicit', models.BooleanField()),
                ('is_playable', models.BooleanField()),
                ('popularity', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(default='Track', max_length=10)),
            ],
        ),
    ]
