# Generated by Django 4.0.2 on 2022-02-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='spotify.artist'),
            preserve_default=False,
        ),
    ]
