# Generated by Django 4.0.2 on 2022-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_track_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artists',
        ),
        migrations.AddField(
            model_name='track',
            name='artists',
            field=models.ManyToManyField(related_name='artists', to='spotify.Artist'),
        ),
    ]
