# Generated by Django 4.0.2 on 2022-02-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_remove_track_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_type',
            field=models.CharField(choices=[('A', 'Album'), ('S', 'Single'), ('C', 'Compilation')], max_length=1),
        ),
    ]
