# Generated by Django 4.0.2 on 2022-02-19 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_alter_track_album_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album_type',
            new_name='albumtypes',
        ),
    ]
