# Generated by Django 4.0.2 on 2022-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_album_track_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(related_name='artists', to='spotify.Album'),
        ),
    ]
