# Generated by Django 4.0.2 on 2022-02-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0005_artist_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='artists', to='spotify.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='tracks', to='spotify.Artist'),
        ),
    ]
