# Generated by Django 4.0.2 on 2022-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_alter_artist_albums_alter_track_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, related_name='tracks', to='spotify.Album'),
        ),
    ]
