# Generated by Django 4.0.2 on 2022-02-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_remove_artist_albums_remove_track_albums_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='artists',
        ),
        migrations.AddField(
            model_name='album',
            name='artist_list',
            field=models.ManyToManyField(related_name='artist_list', to='spotify.Artist'),
        ),
    ]
