# Generated by Django 4.0.2 on 2022-02-20 14:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_alter_track_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='popularity',
            field=models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
