# Generated by Django 4.0.2 on 2022-02-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0011_album_popularity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=210)),
                ('description', models.TextField(blank=True, null=True)),
                ('publisher', models.CharField(max_length=99)),
                ('type', models.CharField(default='show', max_length=10)),
                ('explicit', models.BooleanField(default=True)),
            ],
        ),
    ]
