# Generated by Django 4.0.2 on 2022-02-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spotify', '0012_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('TR', 'Türkiye'), ('DEU', 'Germany'), ('FR', 'France'), ('UK', 'United Kingdom'), ('US', 'United States')], default='Türkiye', max_length=10)),
                ('explicit_content', models.BooleanField(default=False)),
                ('followers', models.PositiveIntegerField()),
                ('type', models.CharField(default='user', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
