# Generated by Django 4.0.2 on 2022-02-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0014_remove_profil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='level',
            field=models.CharField(blank=True, choices=[('PRE', 'PREMIUM'), ('FREE', 'FREE')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='country',
            field=models.CharField(blank=True, choices=[('TR', 'Türkiye'), ('DEU', 'Germany'), ('FR', 'France'), ('UK', 'United Kingdom'), ('US', 'United States')], default='Türkiye', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='explicit_content',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='followers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
