# Generated by Django 4.0.2 on 2022-02-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0015_profil_level_alter_profil_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='level',
            field=models.CharField(blank=True, choices=[('PRE', 'PREMIUM'), ('FREE', 'FREE')], default='FREE', max_length=15),
        ),
    ]
