# Generated by Django 4.0.2 on 2022-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0016_alter_profil_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='top_list',
            field=models.ManyToManyField(related_name='top_list', to='spotify.Track'),
        ),
    ]
