# Generated by Django 4.0.2 on 2022-02-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0017_profil_top_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='followers',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
