# Generated by Django 4.0.2 on 2022-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0019_rename_top_list_profil_top_tracks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='top_tracks',
            field=models.ManyToManyField(related_name='top_tracks', to='spotify.Track'),
        ),
    ]
