# Generated by Django 4.0.2 on 2022-02-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0020_alter_profil_top_tracks'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='top_artists',
            field=models.ManyToManyField(related_name='top_tracks', to='spotify.Artist'),
        ),
    ]
