# Generated by Django 4.0.2 on 2022-02-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0021_profil_top_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileFollowedArtists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_artists', models.ManyToManyField(related_name='followed_artists', to='spotify.Artist')),
            ],
        ),
    ]
