# Generated by Django 4.0.2 on 2022-02-22 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0022_profilefollowedartists'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilefollowedartists',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profil', to='spotify.profil'),
        ),
    ]
