# Generated by Django 4.0.2 on 2022-02-22 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0023_profilefollowedartists_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('collaborative', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('public', models.BooleanField(default=True)),
                ('type', models.CharField(default='playlist', max_length=10)),
                ('followers', models.ManyToManyField(related_name='following_users', to='spotify.Profil')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='spotify.profil')),
                ('tracks', models.ManyToManyField(related_name='tracks', to='spotify.Track')),
            ],
        ),
    ]
