# Generated by Django 4.0.2 on 2022-02-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0024_playlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
